### PR TITLE
Modifications/improvements

### PR DESCRIPTION
**Pull request by arathi-sreekumar**
Hi, I have used this plugin for a project at my workplace and have had to support touch devices and IE9. Hence have made some modifications to support those better, and also one other change as per the request from our UX team. Sending in a pull request in case any of my changes are useful additions to the plugin. I am new to contributing, so if I need to do anything different, please let me know. Cheers!

### CODE REVIEW

**Comment by adjohnson916** [comment]
@arathi-sreekumar Thanks for using the library and for contributing back your changes! It's preferred if you made the changes on different branches in different pull requests, since they are somewhat unrelated, so they can more easily be merged independently. I'm evaluating them now, but looks like these could help address #29 for touch zoom and #32 for IE9 scroll zoom.

**Comment by adjohnson916** [comment]
@arathi-sreekumar I've merged b5d7753 into `master` branch, then modified afterwards. I forgot about the `Event.scale` property. Now that I recall it, I was able to simplify the `pinch` event handler significantly to not rely at all on `Event.deltaX` or `Event.deltaY` (9c9f736). Do you think this will work?

**Comment by arathi-sreekumar** [comment]
It might. I am not an expert on how much cross browser support or device support this will have. Also you might still need a ratio multiplier or it might zoom too much too soon.

**Comment by adjohnson916** [comment]
@arathi-sreekumar With 239a914, can you provide more explanation what you're trying to accomplish? Seems like maybe the existing [`constrainZoomed` option](http://localhost:6246/docs/jsdoc/global.html#MagnificentOptions) could already support your use case?

**Comment by arathi-sreekumar** [comment]
I didnt know what constrained zoom did, I'll give it a try and let you know if its the same as what I was trying to do.

**Comment by arathi-sreekumar** [comment]
I have also added some additional checks to prevent the image moving at all in the horizontal direction if its width is less than container width, and same for vertical. But this might not be needed as a generic solution in the plugin. This was just what our design team felt we needed.

**Comment by arathi-sreekumar** [comment]
Sorry, didn't notice that one. Will update it.

**Comment by adjohnson916** [comment]
Released `2.1.4` to include some of these changes.

**Comment by adjohnson916** [comment]
@arathi-sreekumar Thanks. Regarding the move constraining, I'd like any additional behaviors to be hidden behind options so they are at least configurable if not preferably opt-in.

**Comment by adjohnson916** [comment]
@arathi-sreekumar Closing this for now, since I merged the stuff I thought was good and ready. We can handle the additional changes in future pull requests.

**Pull request closed without merging**
